### ISSUE TITLE
All requests returns empty object instead of the real response

### ISSUE THREAD

**Issue by junzhengca** [ecrmnn/builtwith#2]
The following code logs `{}` instead of actual response.

```javascript
const builtWith = require('builtwith');

builtWith('github.com')
  .then(response => {
    console.log(response);
    console.log(typeof response);
  })
  .catch(err => {
    console.log(err);
  });
```

Output:

```
{}
object
```

* Version: 1.0.2
* OS: macOS Monterey 12.0 Beta 21A5268h
* Node.js Version: v15.3.0

**Comment by ecrmnn** [comment]
Hi @junzhengca. 
Thanks for letting me know!

I no longer use this library so I wont be updating it.
Feel free to submit a PR and I'll gladly merge it.
